<?php

namespace Database\Seeders;

use App\Models\Tool;
use Illuminate\Database\Seeder;

class ToolSeeder extends Seeder
{
    public function run(): void
    {
        $tools = [
            [
                'name' => 'JSON Formatter & Validator',
                'slug' => 'json-formatter',
                'description' => 'Format, validate, and minify JSON instantly',
                'icon' => '{ }',
                'category' => 'JSON',
                'position' => 1,
                'related_tools' => ['json-to-yaml', 'json-to-csv-converter', 'xml-to-json', 'jwt-decoder'],
            ],
            [
                'name' => 'Base64 Encoder/Decoder',
                'slug' => 'base64-encoder',
                'description' => 'Encode and decode Base64 strings',
                'icon' => '🔐',
                'category' => 'Encoding',
                'position' => 2,
                'related_tools' => ['url-encoder', 'hash-generator', 'jwt-decoder'],
            ],
            [
                'name' => 'Cron Expression Builder',
                'slug' => 'cron-expression-builder',
                'description' => 'Build and validate cron schedule expressions',
                'icon' => '⏰',
                'category' => 'Scheduling',
                'position' => 3,
                'related_tools' => ['timestamp-converter', 'regex-tester', 'uuid-generator'],
            ],
            [
                'name' => 'UUID/ULID Generator',
                'slug' => 'uuid-generator',
                'description' => 'Generate unique identifiers instantly',
                'icon' => '🆔',
                'category' => 'Generators',
                'position' => 4,
                'related_tools' => ['password-generator', 'hash-generator', 'qr-code-generator'],
            ],
            [
                'name' => 'Regex Tester',
                'slug' => 'regex-tester',
                'description' => 'Test and debug regular expressions',
                'icon' => '.*',
                'category' => 'Testing',
                'position' => 5,
                'related_tools' => ['diff-checker', 'word-counter', 'json-formatter'],
            ],
            [
                'name' => 'JWT Decoder',
                'slug' => 'jwt-decoder',
                'description' => 'Decode and inspect JSON Web Tokens',
                'icon' => '🔑',
                'category' => 'Security',
                'position' => 6,
                'related_tools' => ['base64-encoder', 'json-formatter', 'hash-generator', 'password-generator'],
            ],
            [
                'name' => 'Password Generator',
                'slug' => 'password-generator',
                'description' => 'Generate secure random passwords',
                'icon' => '🔐',
                'category' => 'Security',
                'position' => 7,
                'related_tools' => ['hash-generator', 'uuid-generator', 'jwt-decoder'],
            ],
            [
                'name' => 'Hash Generator',
                'slug' => 'hash-generator',
                'description' => 'Generate MD5, SHA-256, SHA-512 hashes',
                'icon' => '#️⃣',
                'category' => 'Security',
                'position' => 8,
                'related_tools' => ['password-generator', 'base64-encoder', 'jwt-decoder'],
            ],
            [
                'name' => 'URL Encoder/Decoder',
                'slug' => 'url-encoder',
                'description' => 'Encode and decode URLs and query strings',
                'icon' => '🔗',
                'category' => 'Encoding',
                'position' => 9,
                'related_tools' => ['base64-encoder', 'qr-code-generator', 'json-formatter'],
            ],
            [
                'name' => 'Lorem Ipsum Generator',
                'slug' => 'lorem-ipsum-generator',
                'description' => 'Generate placeholder text for designs',
                'icon' => '📝',
                'category' => 'Text',
                'position' => 10,
                'related_tools' => ['word-counter', 'diff-checker', 'uuid-generator'],
            ],
            [
                'name' => 'Timestamp Converter',
                'slug' => 'timestamp-converter',
                'description' => 'Convert Unix timestamps to dates',
                'icon' => '🕐',
                'category' => 'Date/Time',
                'position' => 11,
                'related_tools' => ['cron-expression-builder', 'json-formatter', 'uuid-generator'],
            ],
            [
                'name' => 'Color Converter',
                'slug' => 'color-converter',
                'description' => 'Convert between HEX, RGB, HSL formats',
                'icon' => '🎨',
                'category' => 'Design',
                'position' => 12,
            ],
            [
                'name' => 'Word Counter',
                'slug' => 'word-counter',
                'description' => 'Count words, characters, and sentences',
                'icon' => '📝',
                'category' => 'Text',
                'position' => 13,
                'related_tools' => ['lorem-ipsum-generator', 'diff-checker', 'regex-tester'],
            ],
            [
                'name' => 'Image Compressor',
                'slug' => 'image-compressor',
                'description' => 'Compress JPEG, PNG, WebP images',
                'icon' => '🖼️',
                'category' => 'Images',
                'position' => 14,
                'related_tools' => ['qr-code-generator', 'base64-encoder', 'color-converter'],
            ],
            [
                'name' => 'Markdown Preview',
                'slug' => 'markdown-preview',
                'description' => 'Write and preview Markdown with real-time rendering, GitHub Flavored Markdown support, and syntax highlighting',
                'icon' => '📝',
                'category' => 'Text',
                'position' => 16,
                'related_tools' => ['diff-checker', 'word-counter', 'lorem-ipsum-generator'],
            ],
            [
                'name' => 'JSON to CSV Converter',
                'slug' => 'json-to-csv-converter',
                'description' => 'Convert between JSON and CSV formats',
                'icon' => '📊',
                'category' => 'Data',
                'position' => 15,
                'related_tools' => ['json-formatter', 'json-to-yaml', 'xml-to-json'],
            ],
            [
                'name' => 'QR Code Generator',
                'slug' => 'qr-code-generator',
                'description' => 'Create QR codes for URLs, WiFi, contacts, email, SMS, and phone numbers. Customize colors and size, download as PNG or SVG.',
                'icon' => '📱',
                'category' => 'Generators',
                'position' => 17,
                'related_tools' => ['uuid-generator', 'url-encoder', 'password-generator'],
            ],
            [
                'name' => 'Diff Checker',
                'slug' => 'diff-checker',
                'description' => 'Compare two texts and highlight differences instantly',
                'icon' => '↔️',
                'category' => 'Text',
                'position' => 18,
                'related_tools' => ['word-counter', 'regex-tester', 'json-formatter'],
            ],
            [
                'name' => 'JSON to YAML Converter',
                'slug' => 'json-to-yaml',
                'description' => 'Convert JSON data to YAML format for configs, Docker, Kubernetes',
                'icon' => '📋',
                'category' => 'Converter',
                'position' => 19,
                'related_tools' => ['yaml-to-json', 'json-to-csv-converter', 'json-formatter', 'xml-to-json'],
            ],
            [
                'name' => 'YAML to JSON Converter',
                'slug' => 'yaml-to-json',
                'description' => 'Convert YAML configs to JSON format for APIs and data exchange',
                'icon' => '🔄',
                'category' => 'Converter',
                'position' => 20,
                'related_tools' => ['json-to-yaml', 'xml-to-json', 'json-to-csv-converter', 'json-formatter'],
            ],
            [
                'name' => 'XML to JSON Converter',
                'slug' => 'xml-to-json',
                'description' => 'Convert XML data to JSON format. Handles attributes, CDATA, and nested elements',
                'icon' => '📄',
                'category' => 'Converter',
                'position' => 21,
                'related_tools' => ['json-to-yaml', 'yaml-to-json', 'json-to-csv-converter', 'json-formatter'],
            ],
            [
                'name' => 'XML to CSV Converter',
                'slug' => 'xml-to-csv',
                'description' => 'Convert XML data to CSV spreadsheet format for Excel and Google Sheets',
                'icon' => '📊',
                'category' => 'Converter',
                'position' => 22,
                'related_tools' => ['xml-to-json', 'json-to-csv-converter', 'json-to-yaml', 'yaml-to-json'],
            ],
            [
                'name' => 'Twitter Character Counter',
                'slug' => 'twitter-character-counter',
                'description' => 'Count characters for Twitter/X posts with real-time tracking for URLs, mentions, and emojis',
                'icon' => '🐦',
                'category' => 'Text',
                'position' => 23,
                'related_tools' => ['word-counter', 'json-formatter'],
            ],
            [
                'name' => 'Hex to RGB Converter',
                'slug' => 'hex-to-rgb',
                'description' => 'Convert hex color codes to RGB, HSL, and CMYK values with live preview and CSS code generation',
                'icon' => '🎨',
                'category' => 'Converter',
                'position' => 24,
                'related_tools' => ['json-formatter', 'word-counter'],
            ],
            [
                'name' => 'Slug Generator',
                'slug' => 'slug-generator',
                'description' => 'Convert any text to clean, SEO-friendly URL slugs with transliteration, stop word removal, and bulk generation',
                'icon' => '🔗',
                'category' => 'Text',
                'position' => 25,
                'related_tools' => ['url-encoder', 'word-counter', 'lorem-ipsum-generator'],
            ],
            [
                'name' => 'ASCII Table & Generator',
                'slug' => 'ascii-table',
                'description' => 'Complete ASCII reference table with all 128 characters. Search, filter, and convert text to ASCII codes instantly',
                'icon' => '📟',
                'category' => 'Reference',
                'position' => 26,
                'related_tools' => ['base64-encoder', 'text-to-binary', 'hash-generator'],
            ],
            [
                'name' => 'Text to Binary Converter',
                'slug' => 'text-to-binary',
                'description' => 'Convert text to binary code and binary to text instantly with ASCII and UTF-8 encoding support',
                'icon' => '0️⃣1️⃣',
                'category' => 'Converter',
                'position' => 27,
                'related_tools' => ['ascii-table', 'base64-encoder', 'hash-generator'],
            ],
            [
                'name' => 'CSV to XML Converter',
                'slug' => 'csv-to-xml',
                'description' => 'Convert CSV data to well-formatted XML with custom element names, attribute mode, and CDATA support',
                'icon' => '📄',
                'category' => 'Converter',
                'position' => 28,
                'related_tools' => ['xml-to-csv', 'xml-to-json', 'json-to-csv-converter', 'csv-to-sql'],
            ],
            [
                'name' => 'JSON to XML Converter',
                'slug' => 'json-to-xml',
                'description' => 'Convert JSON data to well-formatted XML with custom root elements, smart array handling, and type attributes',
                'icon' => '🔀',
                'category' => 'Converter',
                'position' => 29,
                'related_tools' => ['xml-to-json', 'json-to-yaml', 'json-formatter', 'csv-to-xml'],
            ],
            [
                'name' => 'CSV to SQL Converter',
                'slug' => 'csv-to-sql',
                'description' => 'Generate SQL INSERT, CREATE TABLE, and UPDATE statements from CSV data with auto type detection',
                'icon' => '🗃️',
                'category' => 'Converter',
                'position' => 30,
                'related_tools' => ['csv-to-xml', 'json-to-csv-converter', 'xml-to-csv', 'csv-to-json'],
            ],
            [
                'name' => 'JSON to TypeScript Converter',
                'slug' => 'json-to-typescript',
                'description' => 'Generate TypeScript interfaces and types from JSON data with smart naming, union types, and configurable output',
                'icon' => '📘',
                'category' => 'Converter',
                'position' => 31,
                'related_tools' => ['json-formatter', 'json-to-yaml', 'json-to-xml', 'json-to-csv-converter'],
            ],
            [
                'name' => 'Student Email Signature Generator',
                'slug' => 'student-email-signature-generator',
                'description' => 'Create professional email signatures for students with university, major, graduation year, social links, and multiple templates',
                'icon' => '🎓',
                'category' => 'Generator',
                'position' => 32,
                'related_tools' => ['twitter-character-counter', 'slug-generator', 'word-counter'],
            ],
            [
                'name' => 'Chmod Calculator',
                'slug' => 'chmod-calculator',
                'description' => 'Calculate Linux file permissions with an interactive visual grid. Convert between octal (755) and symbolic (rwxr-xr-x) notation.',
                'icon' => '🔒',
                'category' => 'Developer',
                'position' => 33,
                'related_tools' => ['robots-txt-generator', 'slug-generator', 'ascii-table'],
            ],
            [
                'name' => 'Markdown to HTML Converter',
                'slug' => 'markdown-to-html',
                'description' => 'Convert Markdown syntax to clean HTML code with live preview. Supports headings, lists, tables, code blocks, and GFM extensions.',
                'icon' => '📝',
                'category' => 'Converter',
                'position' => 34,
                'related_tools' => ['base64-encoder', 'url-encoder', 'json-formatter'],
            ],
            [
                'name' => 'Base64 to Image Converter',
                'slug' => 'base64-to-image',
                'description' => 'Decode Base64 strings to viewable and downloadable images. Supports PNG, JPEG, GIF, WebP, SVG with auto-format detection.',
                'icon' => '🖼️',
                'category' => 'Converter',
                'position' => 35,
                'related_tools' => ['base64-encoder', 'base64-decoder', 'image-compressor'],
            ],
            [
                'name' => 'Robots.txt Generator',
                'slug' => 'robots-txt-generator',
                'description' => 'Create robots.txt files with a visual editor. Add rules for search engines and AI bots, set crawl delays, and include sitemaps.',
                'icon' => '🤖',
                'category' => 'Generator',
                'position' => 36,
                'related_tools' => ['chmod-calculator', 'slug-generator', 'markdown-to-html'],
            ],
            [
                'name' => 'Bubble Text Generator',
                'slug' => 'bubble-text-generator',
                'description' => 'Convert your text to bubble letters (ⓑⓤⓑⓑⓛⓔ) instantly for social media, Discord, and more. Copy and paste bubble text anywhere.',
                'icon' => '🫧',
                'category' => 'Text',
                'position' => 37,
                'related_tools' => ['zalgo-text-generator', 'strikethrough-text-generator', 'upside-down-text-generator', 'word-counter'],
            ],
            [
                'name' => 'Strikethrough Text Generator',
                'slug' => 'strikethrough-text-generator',
                'description' => 'Create crossed out text instantly for social media, Discord, and more. Copy and paste strikethrough text anywhere.',
                'icon' => '✂️',
                'category' => 'Text',
                'position' => 38,
                'related_tools' => ['bubble-text-generator', 'zalgo-text-generator', 'upside-down-text-generator', 'word-counter'],
            ],
            [
                'name' => 'Upside Down Text Generator',
                'slug' => 'upside-down-text-generator',
                'description' => 'Flip your text upside down instantly for social media, Discord, and more. Copy and paste flipped text anywhere.',
                'icon' => '🙃',
                'category' => 'Text',
                'position' => 39,
                'related_tools' => ['bubble-text-generator', 'zalgo-text-generator', 'strikethrough-text-generator', 'word-counter'],
            ],
            [
                'name' => 'Zalgo Text Generator',
                'slug' => 'zalgo-text-generator',
                'description' => 'Create creepy glitch text with customizable chaos level instantly. Perfect for Discord, social media, and memes.',
                'icon' => '👾',
                'category' => 'Text',
                'position' => 40,
                'related_tools' => ['bubble-text-generator', 'strikethrough-text-generator', 'upside-down-text-generator', 'word-counter'],
            ],
            [
                'name' => 'Small Text Generator',
                'slug' => 'small-text-generator',
                'description' => 'Convert your text to superscript, subscript, and small caps instantly for social media, Discord, and more. Copy and paste tiny text anywhere.',
                'icon' => '🔤',
                'category' => 'Text',
                'position' => 41,
                'related_tools' => ['bubble-text-generator', 'strikethrough-text-generator', 'upside-down-text-generator', 'zalgo-text-generator'],
            ],
            [
                'name' => 'Morse Code Translator',
                'slug' => 'morse-code-translator',
                'description' => 'Convert text to Morse code and Morse code to text instantly. Listen to audio playback with adjustable speed. Supports letters, numbers, and punctuation.',
                'icon' => '📡',
                'category' => 'Text',
                'position' => 42,
                'related_tools' => ['text-to-binary', 'bubble-text-generator', 'upside-down-text-generator', 'small-text-generator'],
            ],
            [
                'name' => 'Chronological Age Calculator',
                'slug' => 'chronological-age-calculator',
                'description' => 'Calculate your exact age in years, months, days, hours, minutes, and seconds. Find next birthday countdown and zodiac sign.',
                'icon' => '🎂',
                'category' => 'Calculators',
                'position' => 43,
                'related_tools' => ['korean-age-calculator', 'timestamp-converter', 'word-counter'],
            ],
            [
                'name' => 'Korean Age Calculator',
                'slug' => 'korean-age-calculator',
                'description' => 'Calculate your Korean age, international age, and see the difference. Learn how the traditional Korean age system works.',
                'icon' => '🇰🇷',
                'category' => 'Calculators',
                'position' => 44,
                'related_tools' => ['chronological-age-calculator', 'timestamp-converter', 'word-counter'],
            ],
            [
                'name' => 'Crontab Guru',
                'slug' => 'crontab-guru',
                'description' => 'Build, validate, and understand cron expressions with human-readable explanations and next scheduled run times. Interactive crontab editor for developers.',
                'icon' => '⏰',
                'category' => 'Developer',
                'position' => 45,
                'related_tools' => ['timestamp-converter', 'json-formatter', 'regex-tester'],
            ],
            [
                'name' => 'HTTP Status Codes Cheat Sheet',
                'slug' => 'http-status-codes',
                'description' => 'Complete HTTP status codes reference with descriptions, categories, and examples. Search and filter all 1xx-5xx response codes instantly.',
                'icon' => '📡',
                'category' => 'Developer',
                'position' => 46,
                'related_tools' => ['json-formatter', 'regex-tester', 'crontab-guru'],
            ],
            [
                'name' => 'Hex to Binary Converter',
                'slug' => 'hex-to-binary',
                'description' => 'Convert hexadecimal to binary instantly with step-by-step nibble breakdown. Supports batch conversion and reverse binary to hex.',
                'icon' => '🔄',
                'category' => 'Converter',
                'position' => 47,
                'related_tools' => ['text-to-binary', 'ascii-table', 'base64-encoder', 'ip-to-binary'],
            ],
            [
                'name' => 'IP to Binary Converter',
                'slug' => 'ip-to-binary',
                'description' => 'Convert IPv4 addresses to binary notation with octet breakdown, subnet visualization, and CIDR support.',
                'icon' => '🌐',
                'category' => 'Converter',
                'position' => 48,
                'related_tools' => ['hex-to-binary', 'text-to-binary', 'ascii-table', 'base64-encoder'],
            ],
            [
                'name' => 'Octal to Decimal Converter',
                'slug' => 'octal-to-decimal',
                'description' => 'Convert octal (base-8) numbers to decimal (base-10) instantly with step-by-step positional notation breakdown.',
                'icon' => '🔢',
                'category' => 'Converter',
                'position' => 49,
                'related_tools' => ['decimal-to-binary', 'hex-to-binary', 'text-to-binary', 'ascii-table'],
            ],
            [
                'name' => 'Decimal to Binary Converter',
                'slug' => 'decimal-to-binary',
                'description' => 'Convert decimal (base-10) numbers to binary (base-2) instantly with division-remainder breakdown and configurable bit padding.',
                'icon' => '🔢',
                'category' => 'Converter',
                'position' => 50,
                'related_tools' => ['octal-to-decimal', 'hex-to-binary', 'text-to-binary', 'ascii-table'],
            ],
            [
                'name' => 'Decimal to Octal Converter',
                'slug' => 'decimal-to-octal',
                'description' => 'Convert decimal (base-10) numbers to octal (base-8) instantly with step-by-step division breakdown and Unix permission reference.',
                'icon' => '🔢',
                'category' => 'Converter',
                'position' => 51,
                'related_tools' => ['octal-to-decimal', 'decimal-to-binary', 'hex-to-binary', 'binary-to-octal'],
            ],
            [
                'name' => 'Binary to Octal Converter',
                'slug' => 'binary-to-octal',
                'description' => 'Convert binary (base-2) numbers to octal (base-8) instantly with step-by-step 3-bit grouping breakdown.',
                'icon' => '🔢',
                'category' => 'Converter',
                'position' => 52,
                'related_tools' => ['decimal-to-octal', 'octal-to-decimal', 'decimal-to-binary', 'hex-to-binary'],
            ],
            [
                'name' => 'CSS to Tailwind Converter',
                'slug' => 'css-to-tailwind',
                'description' => 'Convert CSS properties to Tailwind CSS utility classes instantly with smart color mapping and arbitrary value support.',
                'icon' => '🎨',
                'category' => 'Converter',
                'position' => 53,
                'related_tools' => ['color-converter', 'hex-to-rgb', 'markdown-to-html', 'json-to-typescript'],
            ],
            [
                'name' => 'JSON to C# Class Generator',
                'slug' => 'json-to-csharp',
                'description' => 'Generate C# classes from JSON data with proper types, nullable properties, and JsonProperty attributes.',
                'icon' => '🔷',
                'category' => 'Converter',
                'position' => 54,
                'related_tools' => ['json-to-typescript', 'json-to-dart', 'json-formatter', 'json-to-yaml'],
            ],
            [
                'name' => 'JSON to Dart Converter',
                'slug' => 'json-to-dart',
                'description' => 'Generate Dart classes from JSON data with factory constructors, toJson methods, and null safety support.',
                'icon' => '🎯',
                'category' => 'Converter',
                'position' => 55,
                'related_tools' => ['json-to-csharp', 'json-to-typescript', 'json-formatter', 'json-to-yaml'],
            ],
            [
                'name' => 'Whitespace Remover',
                'slug' => 'whitespace-remover',
                'description' => 'Remove extra whitespace, leading/trailing spaces, blank lines, and normalize spacing in your text instantly.',
                'icon' => '🧹',
                'category' => 'Text',
                'position' => 56,
                'related_tools' => ['remove-line-breaks', 'word-counter', 'slug-generator', 'lorem-ipsum-generator'],
            ],
            [
                'name' => 'Remove Line Breaks',
                'slug' => 'remove-line-breaks',
                'description' => 'Remove line breaks from text online. Convert multi-line text to a single line with custom separator options.',
                'icon' => '📏',
                'category' => 'Text',
                'position' => 57,
                'related_tools' => ['whitespace-remover', 'word-counter', 'slug-generator', 'lorem-ipsum-generator'],
            ],
            [
                'name' => 'CSV Viewer Online',
                'slug' => 'csv-viewer',
                'description' => 'View and explore CSV files in a sortable, searchable table. Paste or upload CSV data for instant visualization.',
                'icon' => '📊',
                'category' => 'Data',
                'position' => 58,
                'related_tools' => ['tsv-to-csv', 'csv-to-sql', 'csv-to-xml', 'json-to-csv-converter'],
            ],
            [
                'name' => 'TSV to CSV Converter',
                'slug' => 'tsv-to-csv',
                'description' => 'Convert tab-separated values (TSV) to comma-separated values (CSV) instantly. Handles quoted fields and special characters.',
                'icon' => '🔄',
                'category' => 'Converter',
                'position' => 59,
                'related_tools' => ['csv-viewer', 'csv-to-sql', 'csv-to-xml', 'json-to-csv-converter'],
            ],
        ];

        foreach ($tools as $tool) {
            $existing = Tool::where('slug', $tool['slug'])->first();

            if ($existing) {
                // Don't overwrite position on existing tools (managed via admin drag-drop)
                unset($tool['position']);
                $existing->update($tool);
            } else {
                Tool::create($tool);
            }
        }
    }
}
