@push('scripts')
<script>
(function() {
    const stringsEl = document.getElementById('tool-strings');
    const S = {
        generated_comment: stringsEl?.dataset.generatedComment || '# robots.txt generated by hafiz.dev/tools/robots-txt-generator',
        downloaded: stringsEl?.dataset.downloaded || 'robots.txt downloaded',
        copied: stringsEl?.dataset.copied || 'Copied!',
        bot_rule_prefix: stringsEl?.dataset.botRulePrefix || 'Bot Rule #',
        remove: stringsEl?.dataset.remove || 'Remove',
        user_agent: stringsEl?.dataset.userAgent || 'User-agent',
        disallow_label: stringsEl?.dataset.disallowLabel || 'Disallow (paths to block, one per line)',
        allow_label: stringsEl?.dataset.allowLabel || 'Allow (paths to explicitly allow)',
        crawl_delay_label: stringsEl?.dataset.crawlDelayLabel || 'Crawl-delay (seconds)',
    };

    const rulesContainer = document.getElementById('rules-container');
    const robotsOutput = document.getElementById('robots-output');
    const sitemapUrls = document.getElementById('sitemap-urls');
    const btnAddRule = document.getElementById('btn-add-rule');
    const btnCopy = document.getElementById('btn-copy');
    const btnDownload = document.getElementById('btn-download');
    const successNotification = document.getElementById('success-notification');
    const successMessage = document.getElementById('success-message');

    let ruleIndex = 1;

    const presets = {
        'allow-all': {
            rules: [{ agent: '*', disallow: '', allow: '/', delay: '' }],
            sitemap: ''
        },
        'block-all': {
            rules: [{ agent: '*', disallow: '/', allow: '', delay: '' }],
            sitemap: ''
        },
        'wordpress': {
            rules: [{ agent: '*', disallow: '/wp-admin/\n/wp-includes/\n/wp-content/plugins/\n/trackback/\n/feed/\n/comments/\n/?s=\n/search/', allow: '/wp-admin/admin-ajax.php', delay: '' }],
            sitemap: 'https://example.com/sitemap.xml'
        },
        'laravel': {
            rules: [{ agent: '*', disallow: '/admin/\n/storage/\n/vendor/\n/_debugbar/\n/telescope/\n/horizon/', allow: '/', delay: '' }],
            sitemap: 'https://example.com/sitemap.xml'
        },
        'block-ai': {
            rules: [
                { agent: '*', disallow: '', allow: '/', delay: '' },
                { agent: 'GPTBot', disallow: '/', allow: '', delay: '' },
                { agent: 'ChatGPT-User', disallow: '/', allow: '', delay: '' },
                { agent: 'CCBot', disallow: '/', allow: '', delay: '' },
                { agent: 'Google-Extended', disallow: '/', allow: '', delay: '' },
                { agent: 'anthropic-ai', disallow: '/', allow: '', delay: '' },
                { agent: 'ClaudeBot', disallow: '/', allow: '', delay: '' }
            ],
            sitemap: ''
        }
    };

    function createRuleBlock(data) {
        const idx = ruleIndex++;
        const block = document.createElement('div');
        block.className = 'rule-block bg-darkBg rounded-lg p-4 border border-gold/10 mb-4';
        block.dataset.index = idx;

        const isCustom = data && data.agent && !['*','Googlebot','Bingbot','Googlebot-Image','Yandex','Baiduspider','DuckDuckBot','Slurp','facebookexternalhit','Twitterbot','GPTBot','ChatGPT-User','CCBot','anthropic-ai','ClaudeBot','Google-Extended'].includes(data.agent);

        block.innerHTML = `
            <div class="flex items-center justify-between mb-3">
                <h3 class="text-light font-semibold text-sm">${S.bot_rule_prefix}${idx + 1}</h3>
                <button class="remove-rule text-red-400 hover:text-red-300 text-xs cursor-pointer">✕ ${S.remove}</button>
            </div>
            <div class="space-y-3">
                <div>
                    <label class="text-light-muted text-xs mb-1 block">${S.user_agent}</label>
                    <select class="rule-agent w-full bg-darkCard border border-gold/20 rounded-lg px-3 py-2 text-light text-sm focus:border-gold/50 focus:outline-none cursor-pointer">
                        <option value="*" ${(!data || data.agent === '*') ? 'selected' : ''}>* (All bots)</option>
                        <option value="Googlebot" ${data && data.agent === 'Googlebot' ? 'selected' : ''}>Googlebot</option>
                        <option value="Bingbot" ${data && data.agent === 'Bingbot' ? 'selected' : ''}>Bingbot</option>
                        <option value="Googlebot-Image" ${data && data.agent === 'Googlebot-Image' ? 'selected' : ''}>Googlebot-Image</option>
                        <option value="Yandex" ${data && data.agent === 'Yandex' ? 'selected' : ''}>Yandex</option>
                        <option value="Baiduspider" ${data && data.agent === 'Baiduspider' ? 'selected' : ''}>Baiduspider</option>
                        <option value="DuckDuckBot" ${data && data.agent === 'DuckDuckBot' ? 'selected' : ''}>DuckDuckBot</option>
                        <option value="Slurp" ${data && data.agent === 'Slurp' ? 'selected' : ''}>Slurp (Yahoo)</option>
                        <option value="facebookexternalhit" ${data && data.agent === 'facebookexternalhit' ? 'selected' : ''}>Facebook</option>
                        <option value="Twitterbot" ${data && data.agent === 'Twitterbot' ? 'selected' : ''}>Twitterbot</option>
                        <option value="GPTBot" ${data && data.agent === 'GPTBot' ? 'selected' : ''}>GPTBot (OpenAI)</option>
                        <option value="ChatGPT-User" ${data && data.agent === 'ChatGPT-User' ? 'selected' : ''}>ChatGPT-User</option>
                        <option value="CCBot" ${data && data.agent === 'CCBot' ? 'selected' : ''}>CCBot (Common Crawl)</option>
                        <option value="anthropic-ai" ${data && data.agent === 'anthropic-ai' ? 'selected' : ''}>Anthropic AI</option>
                        <option value="ClaudeBot" ${data && data.agent === 'ClaudeBot' ? 'selected' : ''}>ClaudeBot</option>
                        <option value="Google-Extended" ${data && data.agent === 'Google-Extended' ? 'selected' : ''}>Google-Extended (Gemini)</option>
                        <option value="custom" ${isCustom ? 'selected' : ''}>Custom...</option>
                    </select>
                    <input type="text" class="rule-agent-custom w-full bg-darkCard border border-gold/20 rounded-lg px-3 py-2 text-light text-sm mt-2 focus:border-gold/50 focus:outline-none ${isCustom ? '' : 'hidden'}" placeholder="Custom user-agent name" value="${isCustom ? data.agent : ''}">
                </div>
                <div>
                    <label class="text-light-muted text-xs mb-1 block">${S.disallow_label}</label>
                    <textarea class="rule-disallow w-full bg-darkCard border border-gold/20 rounded-lg px-3 py-2 text-light text-sm font-mono focus:border-gold/50 focus:outline-none resize-none" rows="3" placeholder="/admin/&#10;/private/" spellcheck="false">${data ? data.disallow : ''}</textarea>
                </div>
                <div>
                    <label class="text-light-muted text-xs mb-1 block">${S.allow_label}</label>
                    <textarea class="rule-allow w-full bg-darkCard border border-gold/20 rounded-lg px-3 py-2 text-light text-sm font-mono focus:border-gold/50 focus:outline-none resize-none" rows="2" placeholder="/public/" spellcheck="false">${data ? data.allow : ''}</textarea>
                </div>
                <div>
                    <label class="text-light-muted text-xs mb-1 block">${S.crawl_delay_label}</label>
                    <input type="number" class="rule-delay w-32 bg-darkCard border border-gold/20 rounded-lg px-3 py-2 text-light text-sm focus:border-gold/50 focus:outline-none" placeholder="0" min="0" max="60" value="${data ? data.delay : ''}">
                </div>
            </div>
        `;

        return block;
    }

    function generate() {
        const blocks = rulesContainer.querySelectorAll('.rule-block');
        let output = S.generated_comment + '\n\n';

        blocks.forEach((block, i) => {
            const agentSelect = block.querySelector('.rule-agent');
            const agentCustom = block.querySelector('.rule-agent-custom');
            let agent = agentSelect.value;
            if (agent === 'custom') agent = agentCustom.value.trim() || '*';

            const disallowText = block.querySelector('.rule-disallow').value.trim();
            const allowText = block.querySelector('.rule-allow').value.trim();
            const delay = block.querySelector('.rule-delay').value.trim();

            output += 'User-agent: ' + agent + '\n';

            if (allowText) {
                allowText.split('\n').forEach(p => {
                    p = p.trim();
                    if (p) output += 'Allow: ' + p + '\n';
                });
            }

            if (disallowText) {
                disallowText.split('\n').forEach(p => {
                    p = p.trim();
                    if (p) output += 'Disallow: ' + p + '\n';
                });
            } else {
                output += 'Disallow:\n';
            }

            if (delay && parseInt(delay) > 0) {
                output += 'Crawl-delay: ' + delay + '\n';
            }

            if (i < blocks.length - 1) output += '\n';
        });

        // Sitemaps
        const sitemaps = sitemapUrls.value.trim();
        if (sitemaps) {
            output += '\n';
            sitemaps.split('\n').forEach(url => {
                url = url.trim();
                if (url) output += 'Sitemap: ' + url + '\n';
            });
        }

        robotsOutput.value = output;
    }

    function applyPreset(name) {
        const preset = presets[name];
        if (!preset) return;

        rulesContainer.innerHTML = '';
        ruleIndex = 0;

        // First rule uses the existing initial block pattern
        preset.rules.forEach((rule, i) => {
            if (i === 0) {
                // Reuse first block
                const block = createRuleBlock(rule);
                block.querySelector('.remove-rule').classList.add('hidden');
                rulesContainer.appendChild(block);
            } else {
                rulesContainer.appendChild(createRuleBlock(rule));
            }
        });

        sitemapUrls.value = preset.sitemap || '';
        generate();
    }

    function showSuccess(msg) {
        successMessage.textContent = msg;
        successNotification.classList.remove('hidden');
        setTimeout(() => successNotification.classList.add('hidden'), 3000);
    }

    // Events
    btnAddRule.addEventListener('click', function() {
        rulesContainer.appendChild(createRuleBlock(null));
        generate();
    });

    rulesContainer.addEventListener('click', function(e) {
        if (e.target.closest('.remove-rule')) {
            const block = e.target.closest('.rule-block');
            if (rulesContainer.children.length > 1) {
                block.remove();
                generate();
            }
        }
    });

    rulesContainer.addEventListener('change', function(e) {
        if (e.target.classList.contains('rule-agent')) {
            const custom = e.target.closest('.rule-block').querySelector('.rule-agent-custom');
            if (e.target.value === 'custom') {
                custom.classList.remove('hidden');
                custom.focus();
            } else {
                custom.classList.add('hidden');
            }
        }
        generate();
    });

    rulesContainer.addEventListener('input', function() { generate(); });
    sitemapUrls.addEventListener('input', function() { generate(); });

    document.querySelectorAll('.preset-btn').forEach(btn => {
        btn.addEventListener('click', function() { applyPreset(this.dataset.preset); });
    });

    btnCopy.addEventListener('click', function() {
        const output = robotsOutput.value;
        if (!output) return;
        navigator.clipboard.writeText(output).then(() => {
            const orig = this.innerHTML;
            this.innerHTML = '<svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7"></path></svg> ' + S.copied;
            this.classList.add('bg-green-600');
            setTimeout(() => { this.innerHTML = orig; this.classList.remove('bg-green-600'); }, 2000);
        });
    });

    btnDownload.addEventListener('click', function() {
        const output = robotsOutput.value;
        if (!output) return;
        const blob = new Blob([output], { type: 'text/plain;charset=utf-8' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url; a.download = 'robots.txt';
        document.body.appendChild(a); a.click();
        document.body.removeChild(a); URL.revokeObjectURL(url);
        showSuccess(S.downloaded);
    });

    // Initial generate
    generate();
})();
</script>
@endpush
