<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::table('posts', function (Blueprint $table) {
            // Link to blog topic (if auto-generated)
            $table->foreignId('blog_topic_id')
                ->nullable()
                ->after('id')
                ->constrained('blog_topics')
                ->nullOnDelete();

            // Automation flags
            $table->boolean('auto_generated')
                ->default(false)
                ->after('reading_time')
                ->comment('True if generated by AI');

            $table->integer('generation_quality_score')
                ->nullable()
                ->after('auto_generated')
                ->comment('AI self-assessment score 1-10');

            $table->boolean('requires_code_review')
                ->default(false)
                ->after('generation_quality_score')
                ->comment('Flag if code examples need validation');

            // Index for queries
            $table->index('blog_topic_id');
            $table->index('auto_generated');
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::table('posts', function (Blueprint $table) {
            $table->dropForeign(['blog_topic_id']);
            $table->dropIndex(['blog_topic_id']);
            $table->dropIndex(['auto_generated']);
            $table->dropColumn([
                'blog_topic_id',
                'auto_generated',
                'generation_quality_score',
                'requires_code_review',
            ]);
        });
    }
};
