<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class Post extends Model
{
    use HasFactory;

    protected $fillable = [
        'blog_topic_id',
        'title',
        'slug',
        'preview_token',
        'excerpt',
        'content',
        'featured_image',
        'seo_title',
        'seo_description',
        'tags',
        'status',
        'published_at',
        'views',
        'reading_time',
        'auto_generated',
        'generation_quality_score',
        'requires_code_review',
        'publish_to_devto',
        'publish_to_hashnode',
        'publish_to_linkedin',
        'publish_to_medium',
    ];

    protected $casts = [
        'tags' => 'array',
        'published_at' => 'datetime',
        'auto_generated' => 'boolean',
        'requires_code_review' => 'boolean',
        'generation_quality_score' => 'integer',
        'publish_to_devto' => 'boolean',
        'publish_to_hashnode' => 'boolean',
        'publish_to_linkedin' => 'boolean',
        'publish_to_medium' => 'boolean',
    ];

    // Relationships
    public function publications()
    {
        return $this->hasMany(PostPublication::class);
    }

    public function blogTopic()
    {
        return $this->belongsTo(BlogTopic::class, 'blog_topic_id');
    }

    public function generationLogs()
    {
        return $this->hasMany(BlogGenerationLog::class, 'post_id');
    }

    // Scopes
    public function scopePublished($query)
    {
        return $query->where('status', 'published')
                    ->where('published_at', '<=', now());
    }

    public function scopeDraft($query)
    {
        return $query->where('status', 'draft');
    }

    public function scopeAutoGenerated($query)
    {
        return $query->where('auto_generated', true);
    }

    public function scopeManual($query)
    {
        return $query->where('auto_generated', false);
    }

    // Accessors
    public function getReadingTimeAttribute($value)
    {
        // If not set, calculate from content (average 200 words/min)
        if (!$value) {
            $wordCount = str_word_count(strip_tags($this->content));
            return ceil($wordCount / 200);
        }
        return $value;
    }

    public function getExcerptAttribute($value)
    {
        // If excerpt not set, generate from content
        if (!$value) {
            return Str::limit(strip_tags($this->content), 200);
        }
        return $value;
    }

    // Helper method to get the preview URL
    public function getPreviewUrl(): string
    {
        return route('blog.preview', ['token' => $this->preview_token]);
    }

    // Auto-generate slug and preview token from title
    protected static function boot()
    {
        parent::boot();

        static::creating(function ($post) {
            if (empty($post->slug)) {
                $post->slug = Str::slug($post->title);
            }

            // Always generate a preview token for new posts
            if (empty($post->preview_token)) {
                $post->preview_token = (string) Str::uuid();
            }
        });
    }
}
